Coco GitHub Actions and Docker Runner (#67)
* GitHub Action for DEV - build, deploy, test

* Commented out Jenkins steps handed to GitHub Actions

diff --git a/.jenkins/Jenkinsfile b/.jenkins/Jenkinsfile
--- a/.jenkins/Jenkinsfile
+++ b/.jenkins/Jenkinsfile
@@ -14,44 +14,44 @@ pipeline {
         disableResume()
     }
     stages {
-        stage('Startup') {
-            agent { label 'build' }
-            steps {
-                script {
-                    def filesInThisCommitAsString = sh(
-                        script:"git diff --name-only HEAD~1..HEAD | grep '^.jenkins/' || echo -n ''",
-                        returnStatus: false,
-                        returnStdout: true
-                    ).trim()
-                    def hasChangesInPath = (filesInThisCommitAsString.length() > 0)
-                    echo "${filesInThisCommitAsString}"
-                    if (!currentBuild.rawBuild.getCauses()[0].toString().contains('UserIdCause') && !hasChangesInPath){
-                        currentBuild.rawBuild.delete()
-                        error("No changes detected in the path ('^.jenkins/')")
-                    }
-                }
-                echo "Aborting all running jobs ..."
-                script {
-                    abortAllPreviousBuildInProgress(currentBuild)
-                }
-            }
-        }
-        stage('Build') {
-            agent { label 'build' }
-            steps {
-                script {
-                    sh "GIT_BRANCH=${env.CHANGE_BRANCH} ./openshift/scripts/oc_build.sh ${suffix} apply"
-                }
-            }
-        }
-        stage('Deploy (DEV)') {
-            agent { label 'deploy' }
-            steps {
-                script {
-                    sh "./openshift/scripts/oc_deploy.sh ${suffix} apply"
-                }
-            }
-        }
+        // stage('Startup') {
+        //     agent { label 'build' }
+        //     steps {
+        //         script {
+        //             def filesInThisCommitAsString = sh(
+        //                 script:"git diff --name-only HEAD~1..HEAD | grep '^.jenkins/' || echo -n ''",
+        //                 returnStatus: false,
+        //                 returnStdout: true
+        //             ).trim()
+        //             def hasChangesInPath = (filesInThisCommitAsString.length() > 0)
+        //             echo "${filesInThisCommitAsString}"
+        //             if (!currentBuild.rawBuild.getCauses()[0].toString().contains('UserIdCause') && !hasChangesInPath){
+        //                 currentBuild.rawBuild.delete()
+        //                 error("No changes detected in the path ('^.jenkins/')")
+        //             }
+        //         }
+        //         echo "Aborting all running jobs ..."
+        //         script {
+        //             abortAllPreviousBuildInProgress(currentBuild)
+        //         }
+        //     }
+        // }
+        // stage('Build') {
+        //     agent { label 'build' }
+        //     steps {
+        //         script {
+        //             sh "GIT_BRANCH=${env.CHANGE_BRANCH} ./openshift/scripts/oc_build.sh ${suffix} apply"
+        //         }
+        //     }
+        // }
+        // stage('Deploy (DEV)') {
+        //     agent { label 'deploy' }
+        //     steps {
+        //         script {
+        //             sh "./openshift/scripts/oc_deploy.sh ${suffix} apply"
+        //         }
+        //     }
+        // }
         stage('Promote (PROD)') {
             agent { label 'deploy' }
             input {
